#!/usr/bin/env node
/**
 * Build `lib/client.js` and `lib/index.js` with the dsh client-bundle preset.
 *
 * The preset (`packages/client/tsdown.client.ts` in a dsh source checkout)
 * resolves a package through `packages/<group>/<dir>/package.json`, needs the
 * checkout's own tsdown/lightningcss, and bundles the tsc output under
 * `lib/types`. So this script stages a temporary face package inside the
 * checkout, points its `node_modules` at this repo's install, runs tsdown for
 * the Client build face, copies the artifacts back and removes the staging
 * directory again. Nothing in the checkout is modified permanently.
 *
 * Usage: node scripts/build-client.mjs [harness-checkout]
 *   default checkout: $DSH_HARNESS, else ../deepseek-harness beside this repo.
 *
 * Run `npm run build` (tsc) first: the preset consumes `lib/types`.
 */
import { spawnSync } from 'node:child_process'
import { copyFileSync, cpSync, existsSync, mkdirSync, readFileSync, rmSync, symlinkSync, unlinkSync, writeFileSync } from 'node:fs'
import { basename, dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const repo = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const harness = resolve(process.argv[2] ?? process.env.DSH_HARNESS ?? join(repo, '..', '..', 'deepseek-harness'))
const pkg = JSON.parse(readFileSync(join(repo, 'package.json'), 'utf8'))
const preset = join(harness, 'packages', 'client', 'tsdown.client.ts')
const tsdownManifest = join(harness, 'node_modules', 'tsdown', 'package.json')
const tsdown = existsSync(tsdownManifest)
  ? join(harness, 'node_modules', 'tsdown', (() => {
      const bin = JSON.parse(readFileSync(tsdownManifest, 'utf8')).bin
      return typeof bin === 'string' ? bin : bin.tsdown
    })())
  : ''

for (const [what, path] of [['harness checkout', join(harness, 'packages')], ['client preset', preset], ['tsdown', tsdown], ['tsc output', join(repo, 'lib', 'types', 'client', 'index.js')]]) {
  if (!existsSync(path)) {
    console.error(`build-client: missing ${what}: ${path}`)
    process.exit(1)
  }
}

const stage = join(harness, 'packages', 'client', pkg.name.replace(/^.*\//, ''))
if (existsSync(stage)) {
  console.error(`build-client: staging directory already exists, remove it first: ${stage}`)
  process.exit(1)
}

const cleanup = () => {
  if (existsSync(join(stage, 'node_modules'))) unlinkSync(join(stage, 'node_modules'))
  rmSync(stage, { recursive: true, force: true })
}

try {
  mkdirSync(join(stage, 'lib'), { recursive: true })
  writeFileSync(join(stage, 'package.json'), readFileSync(join(repo, 'package.json')))
  writeFileSync(join(stage, 'tsdown.config.ts'), [
    '// generated by scripts/build-client.mjs — temporary face package',
    "import { clientBundle } from '../tsdown.client.ts'",
    `export default clientBundle(${JSON.stringify(pkg.name)}, ['lib/types/index.js'])`,
    '',
  ].join('\n'))
  cpSync(join(repo, 'src'), join(stage, 'src'), { recursive: true })
  cpSync(join(repo, 'lib', 'types'), join(stage, 'lib', 'types'), { recursive: true })
  symlinkSync(join(repo, 'node_modules'), join(stage, 'node_modules'), 'junction')

  const run = spawnSync(process.execPath, [tsdown, '--config-loader', 'native', '--env.DSH_BUILD_FACE', 'client'], { cwd: stage, stdio: 'inherit' })
  if (run.status !== 0) {
    console.error(`build-client: tsdown failed with status ${run.status}`)
    process.exitCode = 1
  } else {
    for (const file of ['client.js', 'client.js.map', 'index.js']) {
      copyFileSync(join(stage, 'lib', file), join(repo, 'lib', file))
      console.log(`build-client: wrote lib/${file}`)
    }
  }
} finally {
  cleanup()
}
